### ISSUE TITLE
skeleton of reshaped site

### ISSUE THREAD

**Issue by e-maud** [impresso/CLEF-HIPE-2020#1]
Hello @PaulSchroeder,

As a suggestion:
- home page: the short 'about' plus a very brief overview of the tasks (?)
- tab 'Overview': a kind of a longer 'about' (does it actually make sense?)
- tab 'News': for updates
- tab 'Tasks': with a longer task description than on home page
- tab 'Datasets': one page that will include corpus selection, description, stats, formats, etc.
- tab 'Evaluation settings': submission formats, scorers
- tab 'Registration & Contact'
- tab 'Important dates'
- tab 'Organizers'
- tab 'References': for some biblio refs

What do you think?

**Comment by PaulSchroeder** [comment]
hi Maud, I think it's great. I ended up using **Type** theme as it is well designed and has the most important features built-in. I created a new branch called `type`

**Comment by PaulSchroeder** [comment]
When you pull it in, you'll find a readme file http://localhost:4000/readme.html  showing where to set up theme options.
The style guide demonstrating pre defined styles is here : http://localhost:4000/style-guide.html
